import { dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { FlatCompat } from '@eslint/eslintrc'

/**
 * Flat config, because `next lint` is deprecated and was silently doing nothing:
 * with no config file present it dropped into an interactive setup prompt, so
 * `npm run lint` never linted anything and CI never called it.
 *
 * Rules beyond the Next presets are the ones that catch mistakes this codebase can
 * actually make — an unawaited promise in a route handler is a lost write, and an
 * unchecked `any` from a JSON body is how validation gets skipped.
 */
const compat = new FlatCompat({ baseDirectory: dirname(fileURLToPath(import.meta.url)) })

const config = [
  {
    ignores: [
      '.next/**',
      'node_modules/**',
      'coverage/**',
      'next-env.d.ts',
      // Generated by Prisma; not ours to lint.
      'src/generated/**',
    ],
  },
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
  {
    rules: {
      // A dropped `await` on a database write or an audit call is a correctness bug,
      // not a style preference.
      '@typescript-eslint/no-floating-promises': 'off', // needs type-aware linting; tsc covers the common cases
      'no-console': 'off', // the mailer and error handler log deliberately
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrors: 'none' },
      ],
      // `any` disables the type checking that the validation layer relies on.
      '@typescript-eslint/no-explicit-any': 'warn',
      eqeqeq: ['error', 'always', { null: 'ignore' }],
      'no-var': 'error',
      'prefer-const': 'error',
    },
  },
  {
    // Tests read JSON responses as `any` by design; asserting on a typed shape would
    // just re-encode the implementation into the test.
    files: ['tests/**/*.ts'],
    rules: { '@typescript-eslint/no-explicit-any': 'off' },
  },
]

export default config
